apiVersion: v1
kind: Secret
metadata:
  name: digital-dance-com
  namespace: docker-pv
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

#---
#
#apiVersion: v1
#kind: Secret
#metadata:
#  name: digital-dance-com
#  namespace: ingress-nginx
#type: Opaque
#data:
#  username: YWRtaW4=
#  password: YWRtaW4xMjM=
#
#
#---
#
#apiVersion: v1
#kind: Secret
#metadata:
#  name: digital-dance-com
#  namespace: kube-system
#type: Opaque
#data:
#  username: YWRtaW4=
#  password: YWRtaW4xMjM=