#apiVersion: v1
#kind: Service
#metadata:
#  name: mq-common-eureka-service1
#spec:
#  type: NodePort
##  containers:
##    - name: mq-common-eureka
##      image: mq-common-eureka:v1
##      imagePullPolicy: Always
##      command: [ "echo", "SUCCESS" ]
##  imagePullSecrets:
##    - name: myregistrykey
#  ports:
#    - name: http
#      port: 8761
#      targetPort: 8761
#      nodePort: 31761
#  selector:
#    name: mq-common-eureka
##      image: index.docker.io/xinyuliu0/my:mq-common-eureka
#apiVersion: v1
#kind: Service
#metadata:
#  name: mq-common-eureka
#spec:
#  type: LoadBalancer
##  containers:
##    - name: mq-common-eureka
##      image: mq-common-eureka:v1
##      imagePullPolicy: Always
##      command: [ "echo", "SUCCESS" ]
##  imagePullSecrets:
##    - name: myregistrykey
#  ports:
#    - name: http
#      port: 8761
#      targetPort: 8761
##      nodePort: 31761
#  externalIPs:
#    - 192.168.99.102
#  selector:
#    name: mq-common-eureka
#    app: mq-common-eureka
###      image: index.docker.io/xinyuliu0/my:mq-common-eureka
apiVersion: v1
kind: Pod
metadata:
  name: zipkin-server-pod
  namespace: docker-pv
  labels:
    app: zipkin-server
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim1
  containers:
    - name: zipkin-server
      image: zipkin-server:v1
      ports:
        - name: http
          containerPort: 7082
          hostIP: 0.0.0.0
          hostPort: 7082
          protocol: TCP
      volumeMounts:
        - mountPath: "/app"
          name: task-pv-storage
#    - name: https
#      containerPort: 443
#      hostIP: 0.0.0.0
#      hostPort: 443
#      protocol: TCP
#    externalIPs:
#      - 192.168.99.102